The final form of hook [from BB snippet]

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,27 +1,83 @@
 #!/bin/sh
 # will automatically start before applying commit and try to convert changed files to unicode
 # should be placed in .git/hooks/
+# NOTE: will fail when file is present in index (git add f) but deleted in working dir (rm f)
 
-for file in $(git diff --cached --name-only --diff-filter=ACMR)
-do
-	echo "--- Checking '$file' ---"
-	if iconv -s -f utf-8 -t utf-8 "$file" > /dev/null 
+endline="-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
+
+echo $endline
+echo " * Starting unicode check..."
+
+# turn off escaping non-ascii characters so тест.файл won't turn to "\321\202\320\265\321\201\321\202.\321\204\320\260\320\271\320\273"
+QP=$(git config --get core.quotepath)
+git config core.quotepath off
+
+# get files to process
+FILES=$(git diff --cached --name-only --diff-filter=ACMR)
+git config core.quotepath $QP
+
+# test if output is non whitespace
+if [[ -z "${FILES// }" ]]
+then
+	echo " * Nothing to check"
+	echo $endline 
+	exit
+fi
+
+
+let total=$(echo "$FILES" | grep -c '^') # "" are necessary for array to be presented one file per line
+let unicoded=0
+let i=0
+unicodedFiles=()
+IFS=$'\n' # to parse files with spaces in name
+
+for f in $FILES
+do	
+	let "i += 1"
+	echo "[$i/$total] --- Checking '$f' ---"
+	
+	if iconv -s -f utf-8 -t utf-8 "$f" > /dev/null # won't mess with already unicoded files
 	then
-        # additional check so the files already in UTF8 won't be messed
 		echo " * Conversion not needed"
+		continue
+	fi
+	
+	if iconv -c -f windows-1251 -t utf-8 "$f" > "$f.utf8"
+	then
+		rm "$f"
+		mv "$f.utf8" "$f"
+		let "unicoded += 1"
+		unicodedFiles+=($f)
+		echo " + Converted"
 	else
-		echo " ~ Trying to convert..."
-		if iconv -c -f windows-1251 -t utf-8 "$file" > "$file.utf8"
-		then
-			rm "$file"
-			mv "$file.utf8" "$file"
-            # TODO: instead of silent add, remember the occasion and stop commit
-			git add "$file"
-			echo "  + Success"
-		else
-			echo "  x Failed"
-			rm "$file.utf8"
-		fi
+		echo " x Couldn't convert, probably binary file"
+		rm "$f.utf8"
 	fi
 done
-echo "Done"
+
+echo "- - - - - - - - - - - - - - - - - - - - - - - - - - -"
+echo "Unicode check finished:  $i files checked"
+
+
+if [ $i -ne $total ]
+then
+	echo " ! ERROR: couldn't parse all $total files!"
+	echo " If this keeps happening, use 'git commit --no-verify' to surpass unicode check"
+	echo $endline 
+	exit 1
+fi
+
+
+if [ "$unicoded" -eq 0 ]
+then
+	echo " * Everything is OK"
+	echo $endline
+else
+	echo "Of them $unicoded with forced unicode:"
+	for f in $unicodedFiles; do
+		echo " - $f"
+	done
+	echo " * Commit aborted, check these files and then  'git add'  them again"
+	echo $endline
+	exit 1 # will prevent commit from succeed
+fi
